### ISSUE TITLE
How to use the licensed version

### ISSUE THREAD

**Issue by valentinhocher** [jscharting/jscharting-vue#5]
Hi,

how do I use the licensed version with the vue wrapper to remove the branding?

Thanks!

**Comment by arthurPuszynski** [comment]
Hello, 

Thank you for your inquiry. One solution is to overwrite the `examples/node_modules/jscharting/dist/jscharting.js` file with the licensed version. 

To set it up, first copy the contents of `jsc/` folder (found in the licensed bundle zip), to `/examples/src/assets/jscharting/`. Then modify the `CopyWebpackPlugin` constructor in `vue.config.js` to this:

```javascript
new CopyWebpackPlugin([
   {
      from: path.join(__dirname, 'src/assets/jscharting/'),
      to: path.join(__dirname, 'node_modules/jscharting/dist/')
   },
   {
      from: path.join(__dirname, 'src/assets/jscharting/'),
      to: path.join(__dirname, 'dist/assets/jscharting/'),
      ignore: ['jscharting.*']
   },
])
```

And run `npm run build`. This will copy the files from the licensed bundle into the locations that are used by the chart and the vue plugin. 

One **caveat** is that you must run `npm run build` before in order to copy the jscharting.js file into node_modules. If you run `start` first, the licensed version will not be copied. 

Alternatively, you can add this script to `examples/package.json`

`"postinstall": "cp ./src/assets/jscharting/jscharting.js ./node_modules/jscharting/dist/",`

And `npm run postinstall` to copy the chart after updating the licensed version—that you keep in `/examples/src/assets/jscharting/`. Or after updating the vue plugin.

Would that work?

**Comment by valentinhocher** [comment]
thanks for the hint. Worked like a charm :-)
